### ISSUE TITLE
Docs for the new async support missing

### ISSUE THREAD

**Issue by jakubadamw** [ihrwein/backoff#14]
They're in the code but cannot be found here: https://docs.rs/backoff/0.2.0/backoff/?search=future.

I'm out of time, so I cannot look into the cause but it's probably trivial.

**Comment by ihrwein** [comment]
Hello! Thanks for reporting this issue!

I think docs.rs needs some additional feature flags to build the code with async support. I've tweaked the configuration in https://github.com/ihrwein/backoff/pull/15 and released `0.2.1`.

I used the `tokio` feature flag, since one of the examples in the repo also uses the Tokio runtime. It can't be turned on along with `async-std`.

**Comment by ihrwein** [comment]
And the module appeared in docs: https://docs.rs/backoff/0.2.1/backoff/future/index.html
