### ISSUE TITLE
Retries will happen beyond `max_elapsed_time`

### ISSUE THREAD

**Issue by dcormier** [ihrwein/backoff#42]
```rust
use chrono::prelude::*;

fn main() {
    let bkoffcfg = backoff::ExponentialBackoff {
        max_interval: Duration::from_secs(5),
        max_elapsed_time: Some(Duration::from_secs(15)),
        ..backoff::ExponentialBackoff::default()
    };
    let max = bkoffcfg
        .max_elapsed_time
        .map(chrono::Duration::from_std)
        .unwrap()
        .unwrap();

    let start = Local::now();
    println!("{} Starting", start.to_rfc3339());
    let _result = backoff::retry(bkoffcfg, || {
        let now = Local::now();
        println!("{} Called ({} elapsed)", now.to_rfc3339(), now - start);
        Result::<(), _>::Err(backoff::Error::Transient(()))
    });
    let finished = Local::now();
    let elapsed = finished - start;
    println!("{} Finished (took {})", finished.to_rfc3339(), elapsed);
    assert!(
        elapsed < max,
        "Max elapsed time was {}, but backoff took {}",
        max,
        elapsed
    );
}
```

Example output:
```text
2021-08-11T11:29:51.579538-04:00 Starting
2021-08-11T11:29:51.580198-04:00 Called (PT0.000660S elapsed)
2021-08-11T11:29:52.271778-04:00 Called (PT0.692240S elapsed)
2021-08-11T11:29:52.805305-04:00 Called (PT1.225767S elapsed)
2021-08-11T11:29:53.951580-04:00 Called (PT2.372042S elapsed)
2021-08-11T11:29:55.591119-04:00 Called (PT4.011581S elapsed)
2021-08-11T11:29:57.967951-04:00 Called (PT6.388413S elapsed)
2021-08-11T11:30:01.500511-04:00 Called (PT9.920973S elapsed)
2021-08-11T11:30:04.147603-04:00 Called (PT12.568065S elapsed)
2021-08-11T11:30:08.863625-04:00 Called (PT17.284087S elapsed)
2021-08-11T11:30:08.863691-04:00 Finished (took PT17.284153S)
panicked at 'Max elapsed time was PT15S, but backoff took PT17.284153S'
```

This should never have happened, since it was already beyond `max_elapsed_time`:

```text
2021-08-11T11:30:08.863625-04:00 Called (PT17.284087S elapsed)
```

When the previous attempt finished, `retry` should have computed when the next attempt would be, checked if it was beyond `max_elapsed_time`, and returned.

**Comment by connec** [comment]
I also hit this recently, and we had some internal discussion about whether the name makes sense or not. I think the name of the field is too strong, vs. what can actually be achieved. Even #43 would allow the time taken for the attempt to exceed the `max_elapsed_time` threshold. Since there's no bound on how long the attempt could take (e.g. imagine retrying a `tokio::time::sleep(...)`), this library could never enforce a `max_elapsed_time` (without wrapping a `tokio::time::timeout` or equivalent).

I had called this `min_retry_duration` in our codebase (e.g., the minimum duration for which to continue retrying), but that was also regarded as confusing. I don't have a better suggestion though.

**Comment by dcormier** [comment]
> Even #43 would allow the time taken for the attempt to exceed the max_elapsed_time threshold. Since there's no bound on how long the attempt could take (e.g. imagine retrying a `tokio::time::sleep(...)`), this library could never enforce a `max_elapsed_time` (without wrapping a `tokio::time::timeout` or equivalent).

For my case, I already control for how long the operation being retried may take, and account for that in the value I set for `max_elapsed_time`. I've found this to work very well when combined with #43.
